version: '3.7'

services:
  # WordPress 1
  wordpress1:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql1
    environment:
      WORDPRESS_DB_HOST: mysql1:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress1
    volumes:
      - wp1_data:/var/www/html  # 只挂载 WordPress 数据
    networks:
      - wp_network

  # MySQL 1
  mysql1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress1
    volumes:
      - mysql1_data:/var/lib/mysql  # 只挂载 MySQL 数据
    networks:
      - wp_network

  # WordPress 2
  wordpress2:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql2
    environment:
      WORDPRESS_DB_HOST: mysql2:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress2
    volumes:
      - wp2_data:/var/www/html  # 只挂载 WordPress 数据
    networks:
      - wp_network

  # MySQL 2
  mysql2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress2
    volumes:
      - mysql2_data:/var/lib/mysql  # 只挂载 MySQL 数据
    networks:
      - wp_network

  # Nginx 反向代理
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"  # 监听 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wp_network

  # Filebeat for WordPress 1
  filebeat1:
    image: elastic/filebeat:7.17.0
    user: root
    volumes:
      - ./filebeat/config/modules.d:/usr/share/filebeat/modules.d
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./filebeat1.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - wordpress1
    command: ["--strict.perms=false"]
    networks:
      - wp_network

  # Filebeat for WordPress 2
  filebeat2:
    image: elastic/filebeat:7.17.0
    user: root
    volumes:
      - ./filebeat/config/modules.d:/usr/share/filebeat/modules.d2
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./filebeat2.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - wordpress2
    command: ["--strict.perms=false"]
    networks:
      - wp_network

  # Metricbeat
  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:7.17.0
  #   user: root
  #   volumes:
  #     - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/log:/var/log:ro
  #   depends_on:
  #     - wordpress1
  #     - wordpress2
  #   command: ["--strict.perms=false"]
  #   networks:
  #     - wp_network

  # Metricbeat for WordPress 1
  metricbeat1:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    user: root
    volumes:
      - ./metricbeat/metricbeat1.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - wordpress1
    command: ["--strict.perms=false"]
    networks:
      - wp_network

  # Metricbeat for WordPress 2
  metricbeat2:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    user: root
    volumes:
      - ./metricbeat/metricbeat2.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - wordpress2
    command: ["--strict.perms=false"]
    networks:
      - wp_network


  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - wp_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - wp_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - wp_network

volumes:
  wp1_data:
  wp2_data:
  mysql1_data:
  mysql2_data:
  esdata:

networks:
  wp_network:
    driver: bridge
