filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    fields:
      log_source: apache2  
    include_lines: ['wordpress2.arp.com'] 

output.logstash:
  hosts: ["logstash:5044"] 
