filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata: ~
    fields:
      service: wordpress1
    include_lines:  # 只包含包含特定模式的日志行
      - "wordpress1.arp.com"  # 只收集包含 "http://wordpress1.arp.com/" 的日志

output.logstash:
  hosts: ["logstash:5044"]
  # hosts: ["http://elasticsearch:9200"]
