filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata: ~
    fields:
      service: wordpress2-apache
    include_lines: 
      - "wordpress2.arp.com" 

output.logstash:
  hosts: ["logstash:5044"]
  # hosts: ["elasticsearch:9200"]
