filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata: ~
    fields:
      service: wordpress1-apache
    include_lines: 
      - "wordpress1.arp.com"

  - type: log
    paths:
      - "./wp-debug.log"  # WordPress 业务日志
    fields:
      service: wordpress1-business

output.logstash:
  hosts: ["logstash:5044"]
  # hosts: ["elasticsearch:9200"]
