filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"  
    fields:
      log_source: apache1  
    include_lines: ['wordpress1.arp.com'] 

  - type: log
    enabled: true
    paths:
      - /var/log/user-activity.log 
    fields:
      log_source: user-activity 

  - type: log
    enabled: true
    paths:
      - /var/log/mysql/slow.log  
    fields:
      log_source: mysql1-slow-query
    multiline.pattern: '^\d{6}'   # MySQL slow query logs start with a date in numeric format
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]  # Logstash server address and port
http:
  enabled: true
  host: "0.0.0.0"
  port: 5066


