metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  # 监控 WordPress 2（Web 服务器 2）的系统指标
  - module: system
    period: 10s
    metricsets: ["cpu", "memory", "filesystem", "network"]
    index: "metricbeat-wordpress2-%{+yyyy.MM.dd}"


setup.dashboards.enabled: true
setup.kibana:
  host: "http://kibana:5601"
setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # 添加不同的索引名称，用于区分 WordPress 1 和 WordPress 2 的数据