metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: system
    period: 10s
    metricsets: ["cpu", "memory", "filesystem", "network"]
    index: "metricbeat-wordpress2-%{+yyyy.MM.dd}"


setup.dashboards.enabled: true
setup.kibana:
  host: "http://kibana:5601"
setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
